# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
#[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
  # We have color support; assume it's compliant with Ecma-48
  # (ISO/IEC-6429). (Lack of such support is extremely rare, and such
  # a case would tend to support setf rather than setaf.)
  color_prompt=yes
    else
  color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\] \[\033[01;34m\]\w \$\[\033[00m\] '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -l'
#alias la='ls -A'
#alias l='ls -CF'

#alias pour mise à jour du pi
alias majrasp='sudo apt-get update && sudo apt-get upgrade && sudo apt-get -y dist-upgrade && sudo rpi-update'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

# -----------------------------------------------------------
PROJET=/home/pi/Projet
export PROJET

#
# -----------------------------------------------------------
DIR_BIN=$PROJET/bin
DIR_ERREUR=$PROJET/erreur
DIR_PARAMETRAGE=$PROJET/parametrage
DIR_SHELL=$PROJET/shell
DIR_FICHIER=$PROJET/fichier
DIR_SOURCE=$PROJET/src
DIR_OBJET=$PROJET/OBJ
DIR_INCLUDE=$PROJET/include

export DIR_INCLUDE
export DIR_OBJET

export DIR_BIN
export DIR_ERREUR
export DIR_PARAMETRAGE
export DIR_SHELL
export DIR_FICHIER
export DIR_SOURCE

# User specific aliases and functions
# ------------------------------------------------------------
alias cdbin='cd $DIR_BIN'
alias cder='cd $DIR_ERREUR'
alias cdfic='cd $DIR_FICHIER'
alias cdsh='cd $DIR_SHELL'
alias cdpa='cd $DIR_PARAMETRAGE'
alias cdin='cd $DIR_INCLUDE'
alias cdobj='cd $DIR_OBJET'
alias m='make'
alias rm='rm -i'
alias cp='cp -i'
alias pp=$(echo " ps -ef | egrep detection.x | egrep -v egrep | awk '{print $2}'")
alias cdsrc='cd $DIR_SOURCE'
#alias lancerdetection="sudo ./lancerprog.sh"
#
# Mise a jour de PATH
# ------------------------------------------------------------
PATH=$PATH:$DIR_BIN:$DIR_SHELL
export PATH
